# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-10 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_userpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPayment',
            new_name='MakePayment',
        ),
    ]
