# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-10 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20190910_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
