# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-10 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20190910_0545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MakePayment',
        ),
    ]
