# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='author',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
