# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190821_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='price',
            new_name='amount',
        ),
    ]
