# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190824_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='viewers',
            field=models.IntegerField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='feature',
            name='contributors',
            field=models.IntegerField(default='0', max_length=4),
        ),
    ]
