# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-24 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0009_auto_20190824_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='contributors',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='viewers',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='featureviews',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
        migrations.AddField(
            model_name='featureviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
