# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20190824_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributors',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='value_collected',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='viewers',
        ),
        migrations.AddField(
            model_name='contributors',
            name='contributors',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contributors',
            name='value_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='feature',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.Contributors'),
        ),
    ]
