# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_auto_20190825_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='amount',
            new_name='price',
        ),
    ]
