# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_auto_20190825_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='value_collected',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
    ]
