# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_auto_20190825_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='contributors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
