# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_auto_20190826_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecontributors',
            name='date_contributed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
