# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bugs_view',
            new_name='new_bug_item',
        ),
    ]
