# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-06 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugcomment',
            name='bug',
        ),
        migrations.AddField(
            model_name='bug_item',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug_item',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug_item',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bug_item',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bugcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugs.bug_item'),
        ),
    ]
