# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190730_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_bug_item',
            new_name='bug_item',
        ),
    ]
