# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bug_item',
            name='upvoted_by',
        ),
        migrations.RemoveField(
            model_name='bug_item',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='bug_item',
            name='views',
        ),
        migrations.AddField(
            model_name='views',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugs.bug_item'),
        ),
        migrations.AddField(
            model_name='views',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
