# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190807_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugcomment',
            name='author_image',
            field=models.CharField(default='profile_image/GOGHex2SIW8EkuCqnT42_385891624.0.1534632092_IS3ewlw.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
