# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_auto_20190812_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug_item',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='bug_item',
            name='author_image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_image'),
        ),
    ]
